#all:
#	nn

#nn:
#	mat.o rand.o net.o
#	g++ mat.o rand.o net.o -o nn

#mat.o:
#	mat.cpp 
#	g++ -c mat.cpp

#rand.o: 
#	randf.cpp
#	g++ -c randf.cpp

#net.o: 
#	nure_net.cpp.cpp
#	g++ -c nure_net.cpp

#clean:
#	rm *o nn
all:
	g++ nure_net.cpp mat.cpp randf.cpp -o nn
